from fastapi import FastAPI
from src.predict import (
    get_latest_v6_row,
    connect_to_hopsworks,
)
import pandas as pd
import time


# ============================================================
# APP
# ============================================================

app = FastAPI(
    title="Karachi AQI Predictor"
)


# ============================================================
# CACHE CONFIGURATION
# ============================================================

# Cached data remains valid for 1 hour.
CACHE_TTL = 3600


# ============================================================
# APPLICATION CACHE
# ============================================================

_prediction_cache = None
_prediction_cache_time = 0

_current_cache = None
_current_cache_time = 0

_history_cache = None
_history_cache_time = 0

# Keep one Hopsworks project connection for the API process.
_hopsworks_project = None


# ============================================================
# HOPSWORKS CONNECTION
# ============================================================

@app.on_event("startup")
async def startup_event():
    """
    Connect to Hopsworks once when the API starts
    and warm the current AQI + prediction caches.
    """

    global _hopsworks_project
    global _prediction_cache
    global _prediction_cache_time
    global _current_cache
    global _current_cache_time

    print("\n--- Warming up API caches ---")

    # --------------------------------------------------------
    # Connect to Hopsworks once
    # --------------------------------------------------------

    _hopsworks_project = connect_to_hopsworks()

    # --------------------------------------------------------
    # Warm current AQI cache
    # --------------------------------------------------------

    print("Loading latest AQI...")

    feature_row = get_latest_v6_row(
        _hopsworks_project
    )

    _current_cache = {
        "timestamp": feature_row["timestamp"].iloc[0],
        "current_aqi": float(
            feature_row["target_aqi"].iloc[0]
        ),
    }

    _current_cache_time = time.time()

    # --------------------------------------------------------
    # Warm prediction cache
    # --------------------------------------------------------

    print("Loading latest saved prediction...")

    try:
        _prediction_cache = read_latest_prediction(
            _hopsworks_project
        )

        _prediction_cache_time = time.time()

        print(
            "--- Latest saved prediction loaded successfully ---"
        )

    except Exception as exc:

        print(
            f"--- Prediction cache warm-up failed: {exc} ---"
        )

        # Do not prevent the API from starting.
        _prediction_cache = None
        _prediction_cache_time = 0

    print("--- API cache warm-up complete ---\n")


# ============================================================
# READ LATEST SAVED PREDICTION
# ============================================================

def read_latest_prediction(project):
    """
    Read the latest prediction already generated by the
    automated prediction pipeline from:

        karachi_aqi_predictions v1

    No model loading or inference is performed here.
    """

    fs = project.get_feature_store()

    prediction_fg = fs.get_feature_group(
        name="karachi_aqi_predictions",
        version=1,
    )

    # Prediction Feature Group is small, so reading it is
    # considerably cheaper than running model inference.
    dataframe = prediction_fg.read(
        dataframe_type="pandas"
    )

    if dataframe is None or dataframe.empty:
        raise RuntimeError(
            "No saved predictions found in karachi_aqi_predictions v1."
        )

    dataframe = dataframe.copy()

    # --------------------------------------------------------
    # Normalize timestamp
    # --------------------------------------------------------

    dataframe["timestamp"] = pd.to_datetime(
        dataframe["timestamp"],
        utc=True,
        errors="coerce",
    )

    dataframe = dataframe.dropna(
        subset=["timestamp"]
    )

    if dataframe.empty:
        raise RuntimeError(
            "Prediction Feature Group contains no valid timestamps."
        )

    # --------------------------------------------------------
    # Get latest prediction row
    # --------------------------------------------------------

    latest = (
        dataframe
        .sort_values("timestamp")
        .iloc[-1]
    )

    # --------------------------------------------------------
    # Preserve the response structure expected by Streamlit
    # --------------------------------------------------------

    result = {
        "timestamp": latest["timestamp"],

        "day1": float(latest["day1"]),
        "day2": float(latest["day2"]),
        "day3": float(latest["day3"]),
    }

    # --------------------------------------------------------
    # Preserve model version information if available
    # --------------------------------------------------------

    for key in [
        "day1_model_version",
        "day2_model_version",
        "day3_model_version",
    ]:
        if key in dataframe.columns:
            result[key] = int(latest[key])

    print(
        f"Latest saved prediction timestamp: "
        f"{latest['timestamp']}"
    )

    return result


# ============================================================
# ROOT
# ============================================================

@app.get("/")
def root():
    return {
        "message": "Karachi AQI Predictor API is running"
    }


# ============================================================
# PREDICTION API
# ============================================================

@app.get("/predict")
def get_prediction():

    global _prediction_cache
    global _prediction_cache_time
    global _hopsworks_project

    now = time.time()

    # --------------------------------------------------------
    # Return cached prediction if still valid.
    # --------------------------------------------------------

    if (
        _prediction_cache is not None
        and now - _prediction_cache_time < CACHE_TTL
    ):

        print(
            "Returning cached saved prediction."
        )

        return _prediction_cache

    # --------------------------------------------------------
    # Read latest prediction already saved by automation.
    # --------------------------------------------------------

    print(
        "Reading latest saved prediction from Hopsworks..."
    )

    if _hopsworks_project is None:
        _hopsworks_project = connect_to_hopsworks()

    result = read_latest_prediction(
        _hopsworks_project
    )

    # --------------------------------------------------------
    # Store result in cache.
    # --------------------------------------------------------

    _prediction_cache = result
    _prediction_cache_time = now

    return result


# ============================================================
# CURRENT AQI API
# ============================================================

@app.get("/current")
def get_current():

    global _current_cache
    global _current_cache_time
    global _hopsworks_project

    now = time.time()

    # --------------------------------------------------------
    # Return cached current AQI.
    # --------------------------------------------------------

    if (
        _current_cache is not None
        and now - _current_cache_time < CACHE_TTL
    ):

        print(
            "Returning cached current AQI."
        )

        return _current_cache

    # --------------------------------------------------------
    # Read latest feature row.
    # --------------------------------------------------------

    print(
        "Reading fresh current AQI..."
    )

    if _hopsworks_project is None:
        _hopsworks_project = connect_to_hopsworks()

    feature_row = get_latest_v6_row(
        _hopsworks_project
    )

    result = {
        "timestamp": feature_row[
            "timestamp"
        ].iloc[0],

        "current_aqi": float(
            feature_row[
                "target_aqi"
            ].iloc[0]
        ),
    }

    # --------------------------------------------------------
    # Store current AQI in cache.
    # --------------------------------------------------------

    _current_cache = result
    _current_cache_time = now

    return result


# ============================================================
# HISTORY API
# ============================================================

@app.get("/history")
def get_history():

    global _history_cache
    global _history_cache_time
    global _hopsworks_project

    now_time = time.time()

    # --------------------------------------------------------
    # Return cached history.
    # --------------------------------------------------------

    if (
        _history_cache is not None
        and now_time - _history_cache_time < CACHE_TTL
    ):

        print(
            "Returning cached history."
        )

        return _history_cache

    # --------------------------------------------------------
    # Connect to Hopsworks.
    # --------------------------------------------------------

    print(
        "Reading fresh 90-day AQI history..."
    )

    if _hopsworks_project is None:
        _hopsworks_project = connect_to_hopsworks()

    fs = _hopsworks_project.get_feature_store()

    feature_group = fs.get_feature_group(
        name="karachi_aqi_features",
        version=6,
    )

    # --------------------------------------------------------
    # Read only the required 90-day window.
    # --------------------------------------------------------

    now = pd.Timestamp.now(
        tz="UTC"
    )

    start_time = (
        now
        - pd.Timedelta(days=90)
    )

    dataframe = feature_group.read(
        start_time=start_time.to_pydatetime(),
        end_time=now.to_pydatetime(),
        dataframe_type="pandas",
    )

    if dataframe is None or dataframe.empty:

        result = {
            "data": []
        }

        _history_cache = result
        _history_cache_time = now_time

        return result

    dataframe = dataframe.copy()

    # --------------------------------------------------------
    # Timestamp conversion.
    # --------------------------------------------------------

    dataframe["timestamp"] = pd.to_datetime(
        dataframe["timestamp"],
        unit="ms",
        utc=True,
        errors="coerce",
    )

    dataframe = dataframe.dropna(
        subset=["timestamp"]
    )

    # --------------------------------------------------------
    # Karachi only.
    # --------------------------------------------------------

    dataframe = dataframe[
        dataframe["city"]
        .astype(str)
        .str.lower()
        == "karachi"
    ].copy()

    # --------------------------------------------------------
    # Required columns only.
    # --------------------------------------------------------

    history_columns = [
        "timestamp",
        "target_aqi",
        "pm25",
        "pm10",
        "ozone",
        "nitrogen_dioxide",
        "sulphur_dioxide",
        "carbon_monoxide",
        "temperature",
        "humidity",
    ]

    available_columns = [
        column
        for column in history_columns
        if column in dataframe.columns
    ]

    dataframe = dataframe[
        available_columns
    ].sort_values(
        "timestamp"
    )

    # --------------------------------------------------------
    # Daily aggregation.
    # --------------------------------------------------------

    dataframe["date"] = (
        dataframe["timestamp"]
        .dt.date
    )

    aggregation_columns = [
        column
        for column in [
            "target_aqi",
            "pm25",
            "pm10",
            "ozone",
            "nitrogen_dioxide",
            "sulphur_dioxide",
            "carbon_monoxide",
            "temperature",
            "humidity",
        ]
        if column in dataframe.columns
    ]

    daily = (
        dataframe
        .groupby(
            "date",
            as_index=False,
        )
        .agg(
            {
                column: "mean"
                for column in aggregation_columns
            }
        )
    )

    daily["date"] = (
        daily["date"]
        .astype(str)
    )

    daily = daily.where(
        pd.notna(daily),
        None,
    )

    result = {
        "data": daily.to_dict(
            orient="records"
        )
    }

    # --------------------------------------------------------
    # Store history in cache.
    # --------------------------------------------------------

    _history_cache = result
    _history_cache_time = now_time

    return result